<?php

$title = 'Cadastrando Usuario';
$this->headTitle($title);
?>

<h1> <?= $this->escapeHtml($title)->url?></h1>

<?php

$form->setAtribute('action'. $this->url('usuario',['action' => 'cadastrar']));
$form->prepare();

$id = $this->form->get('id');
$nome = $this->form->get('nome');
$email = $this->form->get('email');

$nome->setAttribute('class', 'form-control');
$nome->setAttribute('class', 'autofocus');

$submit = $this->form->get('submit');
$submit->setAttribute('class', 'btn-primary btn-lg');
?>

<?= $this->formElement($id)?>

<div class="form-group">
    <div class="col-md-6">
      <?=$this->formLabel($nome)?>
      <?=$this->formElement($nome)?>
      <?=$this->formElementErros()->render($nome, ['class' => 'help-block'])?>
  
    </div>
</div>

<div class="form-group">
    <div class="col-md-12">
      <?=$this->formLabel($email)?>
      <?=$this->formElement($email)?>
      <?=$this->formElementErros()->render($email, ['class' => 'help-block'])?>
  
    </div>
</div>
<div class="row">
<?= $this->formElement($submit) ?>
</div>